import { useState } from "react";
import Icon from "../components/Icon";
import AuthLayout from "../components/AuthLayout";

// Terms of Service page. Design-first stub: placeholder content.
export default function TermsOfService() {
  return (
    <AuthLayout title="Terms of Service" subtitle="Last updated: August 2026">
      <div className="space-y-4 text-sm text-on-surface-variant leading-relaxed">
        <p>
          Welcome to Health Risk Predictor. By accessing or using our platform, you agree to be bound by the following terms and conditions.
        </p>
        <h3 className="text-headline-sm text-on-surface">1. Purpose</h3>
        <p>
          Health Risk Predictor is a healthcare decision-support system that provides machine-learning-based risk stratification for research and decision-support purposes. It is <strong>not a medical diagnostic tool</strong> and should not be used as a substitute for professional medical evaluation.
        </p>
        <h3 className="text-headline-sm text-on-surface">2. Data Usage</h3>
        <p>
          Clinical inputs you provide are used solely for risk assessment calculations. We do not sell, share, or distribute your personal health data to third parties. Data is stored securely and retained only as necessary for platform functionality.
        </p>
        <h3 className="text-headline-sm text-on-surface">3. Limitations</h3>
        <p>
          Results provided by this platform are for informational purposes only. Always consult with a qualified healthcare professional before making any medical decisions based on risk assessments generated by this system.
        </p>
        <h3 className="text-headline-sm text-on-surface">4. Acceptable Use</h3>
        <p>
          You agree not to use this platform for any unlawful purpose, to attempt to gain unauthorized access to any part of the system, or to interfere with the proper working of the platform.
        </p>
        <h3 className="text-headline-sm text-on-surface">5. Changes</h3>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the revised terms.
        </p>
      </div>
    </AuthLayout>
  );
}
